services:
  app:
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    ports:
      - "5173:5173"
    networks:
      - laravel-net
  web:
    build: 
      context: .
      dockerfile: ./apache/Dockerfile  
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
    stdin_open: true
    tty: true
    command: ["httpd", "-D", "FOREGROUND"]
    depends_on:
      - app
    networks:
      - laravel-net
  db:
    image: mysql:9.2.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./db/data:/var/lib/mysql
    networks:
      - laravel-net
networks:
  laravel-net:
